version: '3.8'
name: taskboardcompose
services:
  db:
    container_name: taskDB
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "taskDB"
      POSTGRES_USER: "user1"
      POSTGRES_PASSWORD: "12345"
    volumes:
      - taskDB:/var/lib/postgresql/data

volumes:
  taskDB:
