name: Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'TaskBoardBackEnd/**'
env:
  AZURE_WEBAPP_NAME: "app-taskboard-api-germanywestcentral-001"
jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore TaskBoardBackEnd/TaskBoardAPI

    - name: Run tests
      run: dotnet build TaskBoardBackEnd/TaskBoardAPITests
      run: dotnet build TaskBoardBackEnd/TaskBoardIntegrationTests
      run: dotnet test "TaskBoardAPITests\bin\Debug\net8.0\TaskBoardAPITests.dll"
      run: dotnet test "TaskBoardIntegrationTests\bin\Debug\net8.0\TaskBoardIntegrationTests.dll"

    - name: Build
      run: dotnet build TaskBoardBackEnd/TaskBoardAPI --configuration Release --no-restore

    - name: Publish
      run: dotnet publish TaskBoardBackEnd/TaskBoardAPI --configuration Release --output ./TaskBoardBackEnd/TaskBoardAPI/publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.AZURE_WEBAPP_NAME}}
        slot-name: 'production'
        publish-profile: ${{ secrets.API_PUBLISH_SECRET }}
        package: ./TaskBoardBackEnd/TaskBoardAPI/publish
